### ISSUE TITLE
Macros are not rendered in form receipt

### ISSUE THREAD

**Issue by jonaslepsoy** [enonic/app-formbuilder#1]
After sending a form, the receipt page is shown. Macros that are included in the HTMLarea are not rendered correctly, but appear like so:

```
<div class="xp-form-response">
  <p data-portal-component-type="part">
    <!--#MACRO _name="youtube" url="https://www.youtube.com/watch?v=dQw4w9WgXcQ" _document="__macroDocument2" _body=""-->
  </p>
</div>
```

**Comment by hjelmevold** [comment]
Fixed in v1.1.0

Instead of being inserted on the page through AJAX, the form receipt shown on the page after form submission is now included with the page but hidden on page load, and shown with JavaScript upon a successful form submission.

I can foresee some edge cases where this markup that is hidden using display:none in a style attribute could run prematurely (such as autoplay on embedded video or audio), but I haven't been able to confirm this suspicion during my testing. Please create a new issue if such a problem is discovered.
